language: perl
before_install:
  - perlbrew -f install-cpanm
  - "perl -e 'use Module::CPANfile;print $_,$/ for keys Module::CPANfile->load(q!cpanfile!)->prereq_specs->{configure}->{requires}' | cpanm --notest"
perl:
  - "5.14"
